// import './globals.css'
'use client'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
// import header from '@/app/components/header';
// import body from '@/app/components/body';
// import footer from '@/app/components/footer';
import AppHeader from '@/app/components/header';
import { Container } from 'react-bootstrap';
import AppFooter from '@/app/components/footer';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer} from 'react-toastify';



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <Container>
          {children}

        </Container>
        <AppFooter />
        <ToastContainer />
      </body>
    </html>
  )
}
